# Generated by Django 2.2.1 on 2019-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sms_ID', models.IntegerField()),
                ('Sms_ID_Source', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=20)),
                ('Body', models.TextField()),
                ('Date', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
