# Generated by Django 2.2.1 on 2019-05-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190515_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('RecoId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.URLField()),
                ('Url', models.URLField()),
            ],
        ),
    ]
