# Generated by Django 2.2.1 on 2019-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='Price',
            field=models.FloatField(default=0.0),
        ),
    ]
