# Generated by Django 2.1.5 on 2019-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190724_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
    ]
