# Generated by Django 2.1.5 on 2019-07-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sms_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('TopicId', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=20)),
                ('ProcessedDatetime', models.IntegerField()),
            ],
        ),
    ]
